version: '3'

services:
  kafka1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - 9093:9092
    
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: 192.168.169.25
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.169.25:9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./data/kafka1:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3


  kafka2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - 9094:9092

    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.169.25
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.169.25:9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./data/kafka2:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3


  kafka3:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - 9095:9092

    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.169.25
      KAFKA_ADVERTISED_PORT: 9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.169.25:9095
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./data/kafka3:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3


networks:
  default:
    external:
      name: zoonet